# Generated by Django 3.2 on 2021-05-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.ImageField(blank=True, default=True, null=True, upload_to=''),
        ),
    ]
