# Generated by Django 3.2 on 2021-05-01 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_alt',
        ),
    ]
