# Generated by Django 3.2 on 2021-05-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_email'),
        ('store', '0005_auto_20210501_2344'),
    ]

    operations = [
    ]
