# Generated by Django 3.2 on 2021-05-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_20210504_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descriprion',
        ),
    ]
