# Generated by Django 3.2 on 2021-05-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(choices=[('select', 'SELECT'), ('diesel', 'DIESEL'), ('petrol', 'PETROL')], default='select', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='transmission',
            field=models.CharField(choices=[('select', 'SELECT'), ('manual', 'MANUAL'), ('auto', 'AUTOMATIC')], default='select', max_length=7),
        ),
    ]
