# Generated by Django 3.2 on 2021-05-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210505_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fuel_capacity_unit',
            field=models.CharField(choices=[('select', 'SELECT'), ('liters', 'LITERS'), ('cc', 'CC')], default='liters', max_length=10),
        ),
    ]
