# Generated by Django 3.2 on 2021-05-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210505_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(choices=[('select', 'SELECT'), ('diesel', 'DIESEL'), ('petrol', 'PETROL')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='transmission',
            field=models.CharField(choices=[('select', 'SELECT'), ('Manual', 'MANUAL'), ('Automatic', 'AUTOMATIC')], default='select', max_length=20),
        ),
    ]
