# Generated by Django 3.2 on 2021-05-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210505_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fuel_capacity',
            new_name='engine_capacity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fuel_capacity_unit',
            new_name='engine_capacity_unit',
        ),
    ]
