# Generated by Django 3.2 on 2021-05-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_engine_capacity_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='engine_capacity_unit',
            field=models.CharField(blank=True, choices=[('select', 'SELECT'), ('liter', 'LITERS'), ('cc', 'CC')], default='select', max_length=10, null=True),
        ),
    ]
